#!/bin/sh
# 
# Optionally set password for the system user.
# Copyright 2017 Bitnami.com All Rights Reserved
#

. /opt/bitnami/scripts/init/functions

# when run with --force option, set the password regardless of flag
if [ "x$1" != "x--force" ] ; then
    run_once_globally_check "set_system_user_password"
    if [ $? -ne 0 ]; then
        exit 0
    fi
fi

# generate random password
PASSWD="`get_system_password`"

if [ "x$PASSWD" = "x" ] ; then
  echo "Not setting system user password"
  exit 0
fi


for OSUSER in "`get_system_password_users`" ; do
    echo "[`date`] Setting up password for user ${OSUSER}"
    (echo $PASSWD ; echo $PASSWD) | passwd "${OSUSER}"
done

echo "[`date`] Finished setting system user password"