#!/bin/sh
#
# Create welcome message with access information.
# Copyright 2017 Bitnami.com All Rights Reserved
#

. /opt/bitnami/scripts/init/functions

welcome_message_branding_logo() {
  /bin/echo -e "      ___ _ _                   _               "
  /bin/echo -e "     | _ |_) |_ _ _  __ _ _ __ (_)              "
  /bin/echo -e "     | _ \\\\\\\\ |  _| ' \\\\\\\\/ _\` | '  \\\\\\\\| |    "
  /bin/echo -e "     |___/_|\\\\\\\\__|_|_|\\\\\\\\__,_|_|_|_|_|        "
}



welcome_message_header() {
  /bin/echo -e "\033[0;36m"

  welcome_message_branding_logo

  /bin/echo -e "\033[0m"
  /bin/echo -e "\033[0;36m"
  /bin/echo -e "\033[1m*** Welcome to the Bitnami Odoo Stack ***"
  /bin/echo -e "\033[1m*** Built using Debian 8 - Kernel \\\\r (\\\\l). ***\033[0m"
    
}

welcome_message_with_networking() {
  /bin/echo -e "\033[1;33m"
  if [ "x" != "x" ]; then
    /bin/echo -e "\033[1m*** You can connect to the service using @@HOSTNAME@@  ***"
  else
    /bin/echo -e "\033[1m*** You can access the application at http://@@HOSTNAME@@ ***"
  fi

  if [ "xuser@example.com" != "x" ]; then
    application_password=`get_applications_password`
    if [ "x$application_password" = "x" ] ; then
      application_password='bitnami'
    fi
     /bin/echo -e "\033[1m*** The default username and password is 'user@example.com' and '$application_password'. ***"
  elif [ "xfalse" = "xtrue" ] ; then
    application_password=`get_applications_password`
    if [ "x$application_password" = "x" ] ; then
      application_password='bitnami'
    fi
     /bin/echo -e "\033[1m*** The default password is '$application_password'. ***"
  fi
  if [ "xhttps://docs.bitnami.com/virtual-machine/apps/odoo/" != "x" ]; then
    /bin/echo -e "\033[1m*** You can find out more at https://docs.bitnami.com/virtual-machine/apps/odoo/ ***"
  else
    /bin/echo -e "\033[1m*** Please refer to https://docs.bitnami.com/virtual-machine/ for details. ***\033[0m"
    /bin/echo -e "\033[0m"
  fi
}

welcome_message_no_networking() {
  /bin/echo -e "\033[1;33m"
  /bin/echo -e "\033[1m*** The machine could not configure the network interface. ***"
  /bin/echo -e "\033[1m*** Please visit https://docs.bitnami.com/virtual-machine/ for details. ***\033[0m"
  /bin/echo -e "\033[0m"
}

welcome_message_footer() {
  password=`get_system_password`
  if [ "x$password" != "x" ] ; then
    /bin/echo -e "\033[1;31m"
    /bin/echo -e "******************************************************************************"
    /bin/echo -e "   To access the console, please use login 'bitnami'"
    /bin/echo -e "   and password '$password'"
    /bin/echo -e "******************************************************************************"
  fi
  /bin/echo -e "\033[0m"
}


run_once_globally_check "welcome_message_template"
if [ $? -eq 0 ]; then
  # initialize empty directory for template parts
  mkdir -p "$DATA_DIR/welcome_message.d" && chmod 0700 "$DATA_DIR/welcome_message.d" && rm -f "$DATA_DIR/welcome_message.d/*"
  welcome_message_header >$DATA_DIR/welcome_message.d/header
  welcome_message_with_networking >$DATA_DIR/welcome_message.d/with_networking
  welcome_message_no_networking >$DATA_DIR/welcome_message.d/no_networking
  welcome_message_footer >$DATA_DIR/welcome_message.d/footer
fi

IP=`get_server_domain`

if [ "x$IP" = "x" ] ; then
  if [ -f "/etc/init.d/networking" ]; then
    /etc/init.d/networking force-reload
    IP=`get_server_domain`
  elif [ -f "/etc/init.d/network" ]; then
    /etc/init.d/network force-reload
    IP=`get_server_domain`
  fi
fi

if [ "x$IP" != "x" ] ; then
  cat \
    $DATA_DIR/welcome_message.d/header \
    $DATA_DIR/welcome_message.d/with_networking \
    $DATA_DIR/welcome_message.d/footer \
    | sed "s,@@HOSTNAME@@,$IP,g" \
    >/etc/issue
else
  cat \
    $DATA_DIR/welcome_message.d/header \
    $DATA_DIR/welcome_message.d/no_networking \
    $DATA_DIR/welcome_message.d/footer \
    >/etc/issue
fi